### PR TITLE
0.9.26

### PR DESCRIPTION
**Pull request by jujudusud**
Patched with a diff between 0.9.24 of original caps and 0.9.26 of original caps sources.
Verifications and necessary modifications with mod-sdk.

### CODE REVIEW

**Comment by jujudusud** [comment]
@jesseverhage or @jkbd
Could you please take time to look at that ? 
In actual version, did all the caps plugins working on moddevices ?

**Comment by jujudusud** [comment]
Adding a commit with 'LV2 microVersion 26'

**Comment by steveb** [comment]
I tested all of these on mod-host running on Fedora. Testing wasn't exhaustive but they all did something

**Comment by steveb** [comment]
Can you indicate when this might be merged? cheers

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
